In [1]:
# Dependencies
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import gmaps
#from us import states
import os
import csv

from config import gkey

In [2]:
# File path
census_data = "../Desktop/census_2017_4merge.csv"
atm_data = "../Desktop/ATM_1000x_cleaned_4merge.csv"

# Import the data into a Pandas DataFrame
census_df = pd.read_csv(census_data)
atm_df = pd.read_csv(atm_data)

In [3]:
census_df.head()

,index,Zipcode,Population,White Population,Black Population,Hispanic Population,Asian Population,Median Age,Employment Rate,Unemployment Rate,...,Bachelors,Masters,Professional,Doctorate,Poverty Count,Poverty Rate,White Poverty,Black Poverty,Hispanic Poverty,Asian Poverty
0,7025,23005,16337.0,12962.0,2555.0,786.0,201.0,37.8,52.402522,29.534186,...,2366.0,911.0,171.0,268.0,1665.0,10.191590,1287.0,268.0,304.0,55.0
1,7047,23059,34031.0,23175.0,3230.0,1277.0,6288.0,41.0,53.051629,22.867386,...,7550.0,4350.0,1304.0,843.0,1044.0,3.067791,655.0,249.0,25.0,124.0
2,7048,23060,37381.0,23419.0,7305.0,1857.0,4823.0,37.8,58.486932,20.686980,...,7825.0,3579.0,749.0,337.0,1737.0,4.646746,1038.0,486.0,83.0,144.0
3,7051,23063,4466.0,2735.0,1618.0,112.0,3.0,44.0,51.724138,33.116883,...,457.0,147.0,47.0,34.0,217.0,4.858934,98.0,119.0,0.0,0.0
4,7077,23111,37417.0,32378.0,3276.0,903.0,555.0,42.5,55.621776,24.579736,...,6136.0,1771.0,264.0,246.0,2134.0,5.703290,1559.0,389.0,106.0,62.0

In [4]:
atm_df.head()

,Name,Lat,Lon,zip_code,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,Wells Fargo Bank,37.757910,-77.471018,23005,NaN,NaN,NaN,NaN
1,SunTrust,37.678216,-77.586356,23059,NaN,NaN,NaN,NaN
2,Wells Fargo Bank,37.667405,-77.460081,23059,NaN,NaN,NaN,NaN
3,ATM (East Coast),37.643165,-77.564741,23060,NaN,NaN,NaN,NaN
4,ATM Partners Financia,37.651729,-77.460410,23060,NaN,NaN,NaN,NaN

In [7]:
del atm_df['Unnamed: 4']
del atm_df['Unnamed: 5']
del atm_df['Unnamed: 6']
del atm_df['Unnamed: 7']
atm_df.head()

                    Name        Lat        Lon  zip_code
0       Wells Fargo Bank  37.757910 -77.471018     23005
1               SunTrust  37.678216 -77.586356     23059
2       Wells Fargo Bank  37.667405 -77.460081     23059
3       ATM (East Coast)  37.643165 -77.564741     23060
4  ATM Partners Financia  37.651729 -77.460410     23060

In [10]:
atm_df = atm_df.rename(columns={'zip_code': 'Zipcode'})
atm_df.head

<bound method NDFrame.head of                                         Name        Lat        Lon  Zipcode
0                           Wells Fargo Bank  37.757910 -77.471018    23005
1                                   SunTrust  37.678216 -77.586356    23059
2                           Wells Fargo Bank  37.667405 -77.460081    23059
3                           ATM (East Coast)  37.643165 -77.564741    23060
4                      ATM Partners Financia  37.651729 -77.460410    23060
5                               ATM USA, LLC  37.643165 -77.564741    23060
6                                   BB&T ATM  37.644726 -77.568981    23060
7                           Capital One Bank  37.665000 -77.566974    23060
8                            Cardtronics ATM  37.642153 -77.560612    23060
9                            Cardtronics ATM  37.651995 -77.610965    23060
10                           Cardtronics ATM  37.652052 -77.605303    23060
11                           Carrollton Bank  37.652332 -77.608572    23060
12   Partners Financial Federal Credit Union  37.651727 -77.460464    23060
13      Payment Alliance International, Inc.  37.641777 -77.570920    23060
14                          Wells Fargo Bank  37.642157 -77.565371    23060
15                  Woodforest National Bank  37.652215 -77.608736    23060
16                          Wells Fargo Bank  37.687705 -77.885028    23063
17                           Access to Money  37.598198 -77.349281    23111
18                          American Express  37.597465 -77.340712    23111
19                            ATM (7-Eleven)  37.603521 -77.372356    23111
20                           Cardtronics ATM  37.603544 -77.355475    23111
21                                  SunTrust  37.603918 -77.372875    23111
22             Village Bank (Mechanicsville)  37.602639 -77.373338    23111
23                     Virginia Credit Union  37.615262 -77.320919    23111
24                          Wells Fargo Bank  37.611125 -77.341745    23111
25     Access to Money/ABS (Cash-Management)  37.449494 -77.650539    23112
26                  ATM (Brander Mill Shell)  37.450618 -77.651520    23112
27                    ATM (Lucky's Woodlake)  37.407271 -77.682610    23112
28                       Bank of America ATM  37.449375 -77.649781    23112
29                                        BP  37.407270 -77.682599    23112
..                                       ...        ...        ...      ...
118                      ATM (Street Corner)  37.508459 -77.609682    23235
119                              Cardtronics  37.503483 -77.604646    23235
120                          Cardtronics ATM  37.509330 -77.598565    23235
121                         Wells Fargo Bank  37.446895 -77.572891    23236
122                          Access to Money  37.597138 -77.606578    23238
123                         Bank of Virginia  37.596231 -77.603868    23238
124                             Patterson BP  37.597002 -77.605156    23238
125            ATM (Broad & Pemberton Exxon)  37.640233 -77.560580    23294
126                          ATM Henrico Fcu  37.638411 -77.556495    23294
127                             Citibank ATM  37.640272 -77.558352    23294
128             Henrico Federal Credit Union  37.638435 -77.556492    23294
129                    Virginia Credit Union  37.640120 -77.557642    23294
130                         Wells Fargo Bank  37.540762 -77.430817    23298
131                      Bank of America ATM  37.236464 -77.419876    23806
132                    ATM Argent Federal Cu  37.356981 -77.445593    23831
133                      Bank of America ATM  37.353803 -77.413954    23831
134                         Bank of Virginia  37.357262 -77.441577    23831
135                          Cardtronics ATM  37.356792 -77.446262    23831
136             Faison Financial of Virginia  37.359345 -77.434115    23831
137                       Nationallink, Inc.  37.356165 -77.446779    23831
138                                 SunTrust  37.352934 -77.411922    23831
139                   Village Bank (Chester)  37.356220 -77.445489    23831
140                         Wells Fargo Bank  37.355407 -77.448418    23831
141  Partners Financial Federal Credit Union  37.403120 -77.690211    23832
142                    Virginia Credit Union  37.403281 -77.672491    23832
143                             ATM (Uppy's)  37.289772 -77.597083    23838
144                          Cardtronics ATM  37.354418 -77.595755    23838
145                                   Uppy's  37.289630 -77.596916    23838
146                 ATM (Petrol Midget Mart)  37.291240 -77.292579    23860
147                                 SunTrust  37.302878 -77.287483    23860

[148 rows x 4 columns]>

In [9]:
# Merge two dataframes using an outer join on zipcode as the unique identifying variable
merged_df = pd.merge(census_df, atm_df, on="Zipcode", how="outer")
merged_df

,index,Zipcode,Population,White Population,Black Population,Hispanic Population,Asian Population,Median Age,Employment Rate,Unemployment Rate,...,Doctorate,Poverty Count,Poverty Rate,White Poverty,Black Poverty,Hispanic Poverty,Asian Poverty,Name,Lat,Lon
0,7025.0,23005,16337.0,12962.0,2555.0,786.0,201.0,37.8,52.402522,29.534186,...,268.0,1665.0,10.191590,1287.0,268.0,304.0,55.0,Wells Fargo Bank,37.757910,-77.471018
1,7047.0,23059,34031.0,23175.0,3230.0,1277.0,6288.0,41.0,53.051629,22.867386,...,843.0,1044.0,3.067791,655.0,249.0,25.0,124.0,SunTrust,37.678216,-77.586356
2,7047.0,23059,34031.0,23175.0,3230.0,1277.0,6288.0,41.0,53.051629,22.867386,...,843.0,1044.0,3.067791,655.0,249.0,25.0,124.0,Wells Fargo Bank,37.667405,-77.460081
3,7048.0,23060,37381.0,23419.0,7305.0,1857.0,4823.0,37.8,58.486932,20.686980,...,337.0,1737.0,4.646746,1038.0,486.0,83.0,144.0,ATM (East Coast),37.643165,-77.564741
4,7048.0,23060,37381.0,23419.0,7305.0,1857.0,4823.0,37.8,58.486932,20.686980,...,337.0,1737.0,4.646746,1038.0,486.0,83.0,144.0,ATM Partners Financia,37.651729,-77.460410
5,7048.0,23060,37381.0,23419.0,7305.0,1857.0,4823.0,37.8,58.486932,20.686980,...,337.0,1737.0,4.646746,1038.0,486.0,83.0,144.0,"ATM USA, LLC",37.643165,-77.564741
6,7048.0,23060,37381.0,23419.0,7305.0,1857.0,4823.0,37.8,58.486932,20.686980,...,337.0,1737.0,4.646746,1038.0,486.0,83.0,144.0,BB&T ATM,37.644726,-77.568981
7,7048.0,23060,37381.0,23419.0,7305.0,1857.0,4823.0,37.8,58.486932,20.686980,...,337.0,1737.0,4.646746,1038.0,486.0,83.0,144.0,Capital One Bank,37.665000,-77.566974
8,7048.0,23060,37381.0,23419.0,7305.0,1857.0,4823.0,37.8,58.486932,20.686980,...,337.0,1737.0,4.646746,1038.0,486.0,83.0,144.0,Cardtronics ATM,37.642153,-77.560612
9,7048.0,23060,37381.0,23419.0,7305.0,1857.0,4823.0,37.8,58.486932,20.686980,...,337.0,1737.0,4.646746,1038.0,486.0,83.0,144.0,Cardtronics ATM,37.651995,-77.610965
10,7048.0,23060,37381.0,23419.0,7305.0,1857.0,4823.0,37.8,58.486932,20.686980,...,337.0,1737.0,4.646746,1038.0,486.0,83.0,144.0,Cardtronics ATM,37.652052,-77.605303
11,7048.0,23060,37381.0,23419.0,7305.0,1857.0,4823.0,37.8,58.486932,20.686980,...,337.0,1737.0,4.646746,1038.0,486.0,83.0,144.0,Carrollton Bank,37.652332,-77.608572
12,7048.0,23060,37381.0,23419.0,7305.0,1857.0,4823.0,37.8,58.486932,20.686980,...,337.0,1737.0,4.646746,1038.0,486.0,83.0,144.0,Partners Financial Federal Credit Union,37.651727,-77.460464
13,7048.0,23060,37381.0,23419.0,7305.0,1857.0,4823.0,37.8,58.486932,20.686980,...,337.0,1737.0,4.646746,1038.0,486.0,83.0,144.0,"Payment Alliance International, Inc.",37.641777,-77.570920
14,7048.0,23060,37381.0,23419.0,7305.0,1857.0,4823.0,37.8,58.486932,20.686980,...,337.0,1737.0,4.646746,1038.0,486.0,83.0,144.0,Wells Fargo Bank,37.642157,-77.565371
15,7048.0,23060,37381.0,23419.0,7305.0,1857.0,4823.0,37.8,58.486932,20.686980,...,337.0,1737.0,4.646746,1038.0,486.0,83.0,144.0,Woodforest National Bank,37.652215,-77.608736
16,7051.0,23063,4466.0,2735.0,1618.0,112.0,3.0,44.0,51.724138,33.116883,...,34.0,217.0,4.858934,98.0,119.0,0.0,0.0,Wells Fargo Bank,37.687705,-77.885028
17,7077.0,23111,37417.0,32378.0,3276.0,903.0,555.0,42.5,55.621776,24.579736,...,246.0,2134.0,5.703290,1559.0,389.0,106.0,62.0,Access to Money,37.598198,-77.349281
18,7077.0,23111,37417.0,32378.0,3276.0,903.0,555.0,42.5,55.621776,24.579736,...,246.0,2134.0,5.703290,1559.0,389.0,106.0,62.0,American Express,37.597465,-77.340712
19,7077.0,23111,37417.0,32378.0,3276.0,903.0,555.0,42.5,55.621776,24.579736,...,246.0,2134.0,5.703290,1559.0,389.0,106.0,62.0,ATM (7-Eleven),37.603521,-77.372356
20,7077.0,23111,37417.0,32378.0,3276.0,903.0,555.0,42.5,55.621776,24.579736,...,246.0,2134.0,5.703290,1559.0,389.0,106.0,62.0,Cardtronics ATM,37.603544,-77.355475
21,7077.0,23111,37417.0,32378.0,3276.0,903.0,555.0,42.5,55.621776,24.579736,...,246.0,2134.0,5.703290,1559.0,389.0,106.0,62.0,SunTrust,37.603918,-77.372875
22,7077.0,23111,37417.0,32378.0,3276.0,903.0,555.0,42.5,55.621776,24.579736,...,246.0,2134.0,5.703290,1559.0,389.0,106.0,62.0,Village Bank (Mechanicsville),37.602639,-77.373338
23,7077.0,23111,37417.0,32378.0,3276.0,903.0,555.0,42.5,55.621776,24.579736,...,246.0,2134.0,5.703290,1559.0,389.0,106.0,62.0,Virginia Credit Union,37.615262,-77.320919
24,7077.0,23111,37417.0,32378.0,3276.0,903.0,555.0,42.5,55.621776,24.579736,...,246.0,2134.0,5.703290,1559.0,389.0,106.0,62.0,Wells Fargo Bank,37.611125,-77.341745
25,7078.0,23112,52485.0,39619.0,8325.0,2509.0,1855.0,37.7,55.629227,21.604268,...,824.0,1713.0,3.263790,885.0,648.0,48.0,19.0,Access to Money/ABS (Cash-Management),37.449494,-77.650539
26,7078.0,23112,52485.0,39619.0,8325.0,2509.0,1855.0,37.7,55.629227,21.604268,...,824.0,1713.0,3.263790,885.0,648.0,48.0,19.0,ATM (Brander Mill Shell),37.450618,-77.651520
27,7078.0,23112,52485.0,39619.0,8325.0,2509.0,1855.0,37.7,55.629227,21.604268,...,824.0,1713.0,3.263790,885.0,648.0,48.0,19.0,ATM (Lucky's Woodlake),37.407271,-77.682610
28,7078.0,23112,52485.0,39619.0,8325.0,2509.0,1855.0,37.7,55.629227,21.604268,...,824.0,1713.0,3.263790,885.0,648.0,48.0,19.0,Bank of America ATM,37.449375,-77.649781
29,7078.0,23112,52485.0,39619.0,8325.0,2509.0,1855.0,37.7,55.629227,21.604268,...,824.0,1713.0,3.263790,885.0,648.0,48.0,19.0,BP,37.407270,-77.682599
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118,7133.0,23235,31936.0,22467.0,6330.0,2368.0,922.0,43.2,55.673848,27.345316,...,522.0,1915.0,5.996368,1387.0,240.0,487.0,0.0,Cardtronics,37.503483,-77.604646
119,7133.0,23235,31936.0,22467.0,6330.0,2368.0,922.0,43.2,55.673848,27.345316,...,522.0,1915.0,5.996368,1387.0,240.0,487.0,0.0,Cardtronics ATM,37.509330,-77.598565
120,7134.0,23236,26534.0,18588.0,5481.0,1805.0,1106.0,41.7,54.450893,26.434009,...,279.0,1860.0,7.009874,1120.0,459.0,420.0,40.0,Wells Fargo Bank,37.446895,-77.572891
121,7136.0,23238,26133.0,20676.0,3180.0,1369.0,1186.0,44.4,54.884629,27.448054,...,518.0,1943.0,7.435044,1220.0,395.0,375.0,76.0,Access to Money,37.597138,-77.606578
122,7136.0,23238,26133.0,20676.0,3180.0,1369.0,1186.0,44.4,54.884629,27.448054,...,518.0,1943.0,7.435044,1220.0,395.0,375.0,76.0,Bank of Virginia,37.596231,-77.603868
123,7136.0,23238,26133.0,20676.0,3180.0,1369.0,1186.0,44.4,54.884629,27.448054,...,518.0,1943.0,7.435044,1220.0,395.0,375.0,76.0,Patterson BP,37.597002,-77.605156
124,7138.0,23294,17848.0,10152.0,3058.0,1107.0,3603.0,32.0,57.401390,21.571044,...,146.0,1834.0,10.275661,1018.0,414.0,407.0,192.0,ATM (Broad & Pemberton Exxon),37.640233,-77.560580
125,7138.0,23294,17848.0,10152.0,3058.0,1107.0,3603.0,32.0,57.401390,21.571044,...,146.0,1834.0,10.275661,1018.0,414.0,407.0,192.0,ATM Henrico Fcu,37.638411,-77.556495
126,7138.0,23294,17848.0,10152.0,3058.0,1107.0,3603.0,32.0,57.401390,21.571044,...,146.0,1834.0,10.275661,1018.0,414.0,407.0,192.0,Citibank ATM,37.640272,-77.558352
127,7138.0,23294,17848.0,10152.0,3058.0,1107.0,3603.0,32.0,57.401390,21.571044,...,146.0,1834.0,10.275661,1018.0,414.0,407.0,192.0,Henrico Federal Credit Union,37.638435,-77.556492
128,7138.0,23294,17848.0,10152.0,3058.0,1107.0,3603.0,32.0,57.401390,21.571044,...,146.0,1834.0,10.275661,1018.0,414.0,407.0,192.0,Virginia Credit Union,37.640120,-77.557642
129,7259.0,23806,1788.0,36.0,1726.0,35.0,0.0,19.4,45.190157,54.809843,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,Bank of America ATM,37.236464,-77.419876
130,7266.0,23831,36682.0,24524.0,9231.0,2708.0,830.0,38.4,52.742490,25.772859,...,241.0,2226.0,6.068371,1078.0,776.0,150.0,7.0,ATM Argent Federal Cu,37.356981,-77.445593
131,7266.0,23831,36682.0,24524.0,9231.0,2708.0,830.0,38.4,52.742490,25.772859,...,241.0,2226.0,6.068371,1078.0,776.0,150.0,7.0,Bank of America ATM,37.353803,-77.413954
132,7266.0,23831,36682.0,24524.0,9231.0,2708.0,830.0,38.4,52.742490,25.772859,...,241.0,2226.0,6.068371,1078.0,776.0,150.0,7.0,Bank of Virginia,37.357262,-77.441577
133,7266.0,23831,36682.0,24524.0,9231.0,2708.0,830.0,38.4,52.742490,25.772859,...,241.0,2226.0,6.068371,1078.0,776.0,150.0,7.0,Cardtronics ATM,37.356792,-77.446262
134,7266.0,23831,36682.0,24524.0,9231.0,2708.0,830.0,38.4,52.742490,25.772859,...,241.0,2226.0,6.068371,1078.0,776.0,150.0,7.0,Faison Financial of Virginia,37.359345,-77.434115
135,7266.0,23831,36682.0,24524.0,9231.0,2708.0,830.0,38.4,52.742490,25.772859,...,241.0,2226.0,6.068371,1078.0,776.0,150.0,7.0,"Nationallink, Inc.",37.356165,-77.446779
136,7266.0,23831,36682.0,24524.0,9231.0,2708.0,830.0,38.4,52.742490,25.772859,...,241.0,2226.0,6.068371,1078.0,776.0,150.0,7.0,SunTrust,37.352934,-77.411922
137,7266.0,23831,36682.0,24524.0,9231.0,2708.0,830.0,38.4,52.742490,25.772859,...,241.0,2226.0,6.068371,1078.0,776.0,150.0,7.0,Village Bank (Chester),37.356220,-77.445489
138,7266.0,23831,36682.0,24524.0,9231.0,2708.0,830.0,38.4,52.742490,25.772859,...,241.0,2226.0,6.068371,1078.0,776.0,150.0,7.0,Wells Fargo Bank,37.355407,-77.448418
139,7267.0,23832,35523.0,24222.0,8631.0,3548.0,1089.0,37.2,55.459843,23.173718,...,397.0,2370.0,6.671734,1651.0,313.0,657.0,157.0,Partners Financial Federal Credit Union,37.403120,-77.690211
140,7267.0,23832,35523.0,24222.0,8631.0,3548.0,1089.0,37.2,55.459843,23.173718,...,397.0,2370.0,6.671734,1651.0,313.0,657.0,157.0,Virginia Credit Union,37.403281,-77.672491
141,7272.0,23838,16426.0,13877.0,1972.0,245.0,110.0,45.2,55.162547,24.150737,...,190.0,886.0,5.393888,789.0,74.0,0.0,2.0,ATM (Uppy's),37.289772,-77.597083
142,7272.0,23838,16426.0,13877.0,1972.0,245.0,110.0,45.2,55.162547,24.150737,...,190.0,886.0,5.393888,789.0,74.0,0.0,2.0,Cardtronics ATM,37.354418,-77.595755
143,7272.0,23838,16426.0,13877.0,1972.0,245.0,110.0,45.2,55.162547,24.150737,...,190.0,886.0,5.393888,789.0,74.0,0.0,2.0,Uppy's,37.289630,-77.596916
144,7286.0,23860,30983.0,15814.0,12624.0,2224.0,425.0,37.8,43.291482,38.030533,...,130.0,5361.0,17.303037,2310.0,2625.0,388.0,43.0,ATM (Petrol Midget Mart),37.291240,-77.292579
145,7286.0,23860,30983.0,15814.0,12624.0,2224.0,425.0,37.8,43.291482,38.030533,...,130.0,5361.0,17.303037,2310.0,2625.0,388.0,43.0,SunTrust,37.302878,-77.287483
146,NaN,23232,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ATM,37.560666,-77.445796
147,NaN,23298,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Wells Fargo Bank,37.540762,-77.430817

In [16]:
zipgroup = merged_df.groupby("Zipcode")["Name"].count()
zip_reindexed = zipgroup.reset_index()
zip_indexsort = zip_reindexed.sort_values(["Name"], ascending=False)
zip_indexsort

    Zipcode  Name
24    23233    20
5     23112    14
2     23060    13
14    23223    11
16    23225    10
32    23831     9
4     23111     8
11    23219     6
21    23230     5
10    23139     5
29    23294     5
26    23235     4
6     23113     4
13    23222     3
28    23238     3
34    23838     3
1     23059     2
35    23860     2
25    23234     2
15    23224     2
33    23832     2
27    23236     1
31    23806     1
30    23298     1
0     23005     1
23    23232     1
22    23231     1
20    23229     1
19    23228     1
17    23226     1
12    23221     1
9     23120     1
8     23116     1
7     23114     1
3     23063     1
18    23227     1

In [ ]:
#Configure gmaps with API key
gmaps.configure(api_key=gkey)

In [ ]:
## Store zip codes in locations 
locations = merged_df[["Lat", "Lng"]].astype(float)

# Convert Poverty Rate to float and store
# HINT: be sure to handle NaN values
atm_count = merged_df["ATM_count"].astype(float)

In [ ]:
## Create a poverty Heatmap layer
fig = gmaps.figure()

heat_layer = gmaps.heatmap_layer(locations, weights=atm_count, 
                                 dissipating=False, max_intensity=100,
                                 point_radius = 1)

# Adjust heat_layer setting to help with heatmap dissipating on zoom
heat_layer.dissipating = False
heat_layer.max_intensity = 100
heat_layer.point_radius = 1

fig.add_layer(heat_layer)

fig